version: '2'
services:
  unbound:
    image: shuosc/unbound:latest
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /home/docker-unbound/supervisor.conf.d:/etc/supervisor/conf.d
      - /home/docker-unbound/unbound.conf.d:/usr/local/etc/unbound/conf.d
