version: '2'
services:
  unbound:
    image: shuosc/unbound:latest
    restart: always
    ports:
      - "54:53/tcp"
      - "54:53/udp"
    volumes:
      - /home/docker-unbound/supervisor:/etc/supervisor/
      - /home/docker-unbound/unbound:/usr/local/etc/unbound/
